# Required libraries----
if(!require(shiny)){
  install.packages('shiny')
  library(shiny)
}else{
  library(shiny)
}

if(!require(tibble)){
  install.packages('tibble')
  library(tibble)
}else{
  library(tibble)
}

if(!require(stringr)){
  install.packages('stringr')
  library(stringr)
}else{
  library(stringr)
}

if(!require(rollama)){
  install.packages('rollama')
  library(rollama)
  ping_ollama()
  pull_model("llama3.2:3b")
}else{
  library(rollama)
  ping_ollama()
}

if(!require(parallel)){
  install.packages('parallel')
  library(parallel)
}else{
  library(parallel)
}

if(!require(doMC)){
  install.packages('doMC')
  library(doMC)
}else{
  library(doMC)
}

if(!require(svMisc)){
  install.packages('svMisc')
  library(svMisc)
}else{
  library(svMisc)
}


if(!require(qdapDictionaries)){
  install.packages('qdapDictionaries')
  library(qdapDictionaries)
}else{
  library(qdapDictionaries)
}

if(!require(DT)){
  install.packages('DT')
  library(DT)
}else{
  library(DT)
}

# if(!require(shinylive)){
#   install.packages('shinylive')
#   library(shinylive)
# }else{
#   library(shinylive)
# }
# 
# if(!require(httpuv)){
#   install.packages('httpuv')
#   library(httpuv)
# }else{
#   library(httpuv)
# }


# Functions----

get_new_sentence = function(my_sentence = NULL,
                            sample_size = 5,
                            variants = 10,
                            pop_size = 100,
                            ngenerations = 100,
                            mutation_rate = 10^(-1),
                            recombination_rate = 10^(-1)
){
  
  # Define dictionary
  removed_letters = letters[!(letters %in% c('a', 'e', 'i', 'o', 'u'))]
  ## Remove single consonants from dictionary, There are still some rear combination of characters that are included in the dictionary
  word_list = GradyAugmented[!(GradyAugmented %in% c(removed_letters, 'ch', 'sh'))] 
  
  # Convert all characters in the the sentence to lowercase letters
  my_sentence = tolower(my_sentence)
  
  # Remove final period
  my_sentence = gsub('\\.$', '', my_sentence)
  
  # Paraphrase sentence with llama
  llama_query = paste0("paraphrase the following sentence in ",
                       variants,
                       " different ways: '",
                       my_sentence,
                       "'. Only provide the sentences."
  )
  
  sentences = query(llama_query, model = "llama3.2:3b")
  
  # Transform llama output to a vector and conbine it with the original sentence
  sentences = sentences[[1]][['message']][['content']]
  sentences = unlist(strsplit(sentences, '(^1\\. |\\\n\\d+\\. )'))
  sentences = c(my_sentence, sentences[sentences != ''])
  sentences = gsub('\\.$', '', sentences)
  
  # Run genealogy
  
  sentence_genealogy = NULL # Empty list to store results of the genealogies in each generation
  
  # Generation zero, pick n (pop_size) sentences with replacement from the vector that contain the original phrase plus the m variants generated by llama
  population_of_sentences = sample(sentences, pop_size, replace = T)
  sentence_genealogy[['Generation_0']] = population_of_sentences
  
  for(generation in 1:ngenerations){ 
    
    gamete_sentences = foreach(parent_sentence_index = 1:length(population_of_sentences), .combine = 'c') %dopar% { # For each parent sentence in the current population,
      
      parent_sentence = sentence_genealogy[[generation]][parent_sentence_index] # pick the parent sentence
      
      my_words = unlist(strsplit(parent_sentence, ' |, |\\. |; |\\-')) # Split the sentence into words
      
      words_length = nchar(my_words) # Count the number of characters of the word
      
      # Define where each word start and end
      words_start = 1
      words_end = NULL
      for(i in 1:length(words_length)){
        if(i == 1){
          words_end = c(words_end, words_start[i] + words_length[i] - 1)
        }else{
          words_start = c(words_start, words_end[i - 1] + 1)
          words_end = c(words_end, words_start[i] + words_length[i] - 1)
        }
      }
      
      # Safe all word separators in a vector
      my_separators = unlist(str_extract_all(parent_sentence, ' |, |\\. |; |\\-'))
      
      # Collapse all words into a single string
      merged_words = paste(my_words, collapse = '')
      
      # Split the sentence into single characters
      merged_words = unlist(strsplit(merged_words, ''))
      
      # For each position in the sentence allows mutation to occurs at the specified mutation rate
      for(i in  1:length(merged_words)){
        
        if(runif(1) <= mutation_rate){# If mutation happens, substitute, delete or insert a random character
          
          merged_words[i] = sample(c(letters, # Substitution 
                                     '', # Deletion
                                     paste(merged_words[i], letters, sep ='') # Insertion
                                     ), 1) 
          
        }
        
      }
      
      # Identify the new words in the mutated sentence
      new_words = NULL
      
      for(i in 1:length(words_start)){ # For each word in the mutated sentence
        
        new_word = paste(merged_words[words_start[i]:words_end[i]], collapse = '') # Extract the word
        
        if(new_word %in% word_list){ # If the word exist in the dictionary
          
          new_words = paste0(new_words, my_separators[i - 1], new_word) # Keep the word
          
        }else{ # else
          
          new_words = paste0(new_words, my_separators[i - 1], my_words[i]) # Keep the previous state of word
          
        }
      }
      
      new_words # Safe words in the gamete sentence, They potential offspring for the next generation
      
    }
    
    # Sexual reproduction 
    
    # Select two random gametes from the current generation to form the sexual stage
    gametes_1 = gamete_sentences[sample(1:length(gamete_sentences), pop_size, replace = T)]
    gametes_2 = gamete_sentences[sample(1:length(gamete_sentences), pop_size, replace = T)]
    
    # Equivalent to the sporozoites in malaria development
    offspring_setences = foreach(offspring_index = 1:pop_size, .combine = 'c') %dopar% { # For each pair of gametes form the zygote and...,
      
      gamete_1 = unlist(strsplit(gametes_1[offspring_index], ' ')) # Pick gamete 1 and split the sentence into words
      
      gamete_2 = unlist(strsplit(gametes_2[offspring_index], ' ')) # Pick gamete 2 and split the sentence into words
      
      # Start meiosis
      
      if(runif(1) <= recombination_rate){ # If recombination occurs
        
        break_point = sample(1:(min(length(gamete_1), length(gamete_2)) - 1), 1) # Identify break point
        
        recombined_gamete_1 = c(gamete_1[1:break_point], gamete_2[(break_point + 1):length(gamete_2)]) # Pick 1st recombinant line
        recombined_gamete_2 = c(gamete_2[1:break_point], gamete_1[(break_point + 1):length(gamete_1)]) # Pick 2nd recombinant line
        
        recombined_gamete_1 = paste(recombined_gamete_1, collapse = ' ') # Collapse words of the 1st recombinant line into a sentence
        recombined_gamete_2 = paste(recombined_gamete_2, collapse = ' ') # Collapse words of the 2nd recombinant line into a sentence
        
      }else{ # If recombination does not occurs the intact sentences pass through the next step of the cycle
        
        recombined_gamete_1 = gamete_1
        recombined_gamete_2 = gamete_2
        
        recombined_gamete_1 = paste(recombined_gamete_1, collapse = ' ')
        recombined_gamete_2 = paste(recombined_gamete_2, collapse = ' ')
        
      }
      
      # Pick randomly one out of two sentences for the next generation
      
      if(sample(1:2, 1) == 1){
        
        offspring_setence = recombined_gamete_1
        
      }else{
        
        offspring_setence = recombined_gamete_2
        
      }
      
      offspring_setence
      
    }
    
    # save results in the list
    sentence_genealogy[[paste0('Generation_',generation)]] = offspring_setences
    
    progress(round(100*generation/ngenerations))
    
  }
  
  # At the end of the simulation pick a random sample
  
  final_generation = sentence_genealogy[[ngenerations + 1]]
  
  result = sample(final_generation, sample_size)
  
  result = data.frame(Sample = paste0('Sample ', 1:length(result)),
                      Output = result
  )
  
  original_setences = 
    data.frame(
      Query = c('Original query', paste0('Paraphrase ', 1:(length(sentences) - 1))),
      Sentence = sentences)
  
  result = list(result = result,
                final_generation = final_generation,
                original_setences = original_setences
                )
  
  return(result)
  
}

# User Interface----
ui <- fluidPage(
  # App inputs
  textAreaInput("query", "Please provide your query:", rows = 4),
  numericInput("sample_size", "Number of sentences you want as an output:", value = 5),
  numericInput("variants", "Number of times you want to paraphrase your sentence:", value = 5),
  numericInput("pop_size", "Define a population size:", value = 100),
  numericInput("ngenerations", "Number of generations:", value = 10),
  numericInput("mutation_rate", "Mutation rate:", value = .1),
  numericInput("recombination_rate", "Recombination rate:", value = .1),
  
  fluidRow(
    actionButton("go", "Go", class = "btn-lg btn-success"),
    actionButton("resample", "Sample")),
  
  # App outputs
  textOutput('query_message'),
  DT::dataTableOutput("original_setences"),
  textOutput('samples_message'),
  DT::dataTableOutput("samples")
)

# Server instructions----
server <- function(input, output, session) {
  
  #query_message = reactive()
  
  results = eventReactive(input$go, {
    get_new_sentence(my_sentence = input$query,
                     sample_size = input$sample_size,
                     variants = input$variants,
                     pop_size = input$pop_size,
                     ngenerations = input$ngenerations,
                     mutation_rate = input$mutation_rate,
                     recombination_rate = input$recombination_rate)
    
  })
  
  #samples = result[[1]]()
  
  query_message = reactive({
    paste0('Your query and the ',
           input$variants, ' different variants create by llama are shown in the next table. Now click on Sample to get your final output')})
  
  output$query_message = renderText(query_message())
  
  output$original_setences = DT::renderDataTable(results()[['original_setences']])
  
  samples_message = reactive({
    paste0('Your ',
           input$sample_size, ' different sample(s) are shown in the next table')
  })

  output$samples_message = renderText(samples_message())
  
  
  newsamples = NULL
  
  newsamples = eventReactive(input$resample, {
    data.frame(Sample = paste0('Sample ', 1:input$sample_size),
               Output = sample(results()[['final_generation']], input$sample_size, replace = T))
  })
  
  output$samples = DT::renderDataTable(
    if(is.null(newsamples)){
      results()[['result']]
    }else{
      newsamples()
      }
    )
}

# Launch the application----
shinyApp(ui, server)
